# Generated by Django 6.0.3 on 2026-04-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('videoId', models.CharField(max_length=50)),
                ('cantor', models.CharField(max_length=100)),
            ],
        ),
    ]
