# Generated by Django 6.0.3 on 2026-08-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
